### ISSUE TITLE
Reduce Image size

### ISSUE THREAD

**Issue by nimarty** [nimarty/hackypi#1]
Current "minimal" image is with 270MB quite big.

**Comment by LinderPi** [comment]
Replacing OpenSSH by dropbear should reduce the image size

**Comment by nimarty** [comment]
Ein Weg die Image Size zu reduzieren ist, die Gesamtgrösse des Root-FS zu reduzieren. Siehe `meta-hackypi/recipes-core/images/hackypi-image.bb`
`IMAGE_ROOTFS_SIZE ?= "8192"`
`IMAGE_ROOTFS_EXTRA_SPACE_append = "${@bb.utils.contains("DISTRO_FEATURES", "systemd", " + 4096", "" ,d)}"`
Das führt aber anschliessend zum Problem, das kein Speicherplatz zum Installieren von Security-Challenges zur Verfügung steht.
Um das Problem zu beheben könnte nach dem Bootvorgang die Datenpartition auf der SD Karte auf die volle Grösse heraufgesetzt werden. Die SD Karte im Raspberry Pi wird wohl >4GB haben, genug Speicherplatz für wohl so einige Security Challenge Packages.
