### ISSUE TITLE
Restart SSH daemon after chatty charly installation

### ISSUE THREAD

**Issue by LinderPi** [nimarty/hackypi#10]
In order to consider modifications on the SSH configuration

**Comment by nimarty** [comment]
good point. this affects all challenges which modify openSSH configuration.

**Comment by nimarty** [comment]
The bug was: after installation of the package the modified openSSH configuration was only applied after a restart. The user expects to be able to tackle the security challenge right after package installation, so this caused a problem.

**Comment by LinderPi** [comment]
Solved in #14
